<a href="https://colab.research.google.com/github/davi-osilva/engenharia-agentes-IA/blob/main/aula005.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Conhecendo o Pandas

In [141]:
import pandas as pd
import numpy as np

# Definindo os dados para as colunas
nomes_produtos = [f"Produto {i+1}" for i in range(50)]
categorias_produtos = np.random.choice(["Eletrônicos", "Livros", "Roupas", "Alimentos", "Brinquedos"], 50)
precos_produtos = np.random.uniform(10.0, 500.0, 50).round(2)
itens_vendidos = np.random.randint(1, 1000, 50)
avaliacoes_produtos = np.random.uniform(1.0, 5.0, 50).round(1)

# Criando o DataFrame
df_produtos = pd.DataFrame({
    "Nome do produto": nomes_produtos,
    "Categoria do produto": categorias_produtos,
    "Preço do produto": precos_produtos,
    "Itens vendidos": itens_vendidos,
    "Avaliação do produto": avaliacoes_produtos
})

In [142]:
df_produtos.head()

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
0,Produto 1,Alimentos,387.27,544,4.6
1,Produto 2,Brinquedos,421.05,208,4.5
2,Produto 3,Brinquedos,171.81,168,4.1
3,Produto 4,Brinquedos,229.73,613,1.7
4,Produto 5,Alimentos,170.04,523,1.8

In [143]:
df_produtos['Categoria do produto']

0       Alimentos
1      Brinquedos
2      Brinquedos
3      Brinquedos
4       Alimentos
5          Roupas
6          Roupas
7          Livros
8       Alimentos
9     Eletrônicos
10         Livros
11         Roupas
12      Alimentos
13      Alimentos
14    Eletrônicos
15     Brinquedos
16         Livros
17     Brinquedos
18         Roupas
19      Alimentos
20    Eletrônicos
21     Brinquedos
22         Roupas
23         Roupas
24         Roupas
25     Brinquedos
26    Eletrônicos
27      Alimentos
28      Alimentos
29         Roupas
30    Eletrônicos
31         Roupas
32     Brinquedos
33         Roupas
34         Roupas
35    Eletrônicos
36      Alimentos
37      Alimentos
38         Livros
39         Livros
40     Brinquedos
41         Roupas
42         Roupas
43     Brinquedos
44     Brinquedos
45    Eletrônicos
46         Livros
47      Alimentos
48         Roupas
49     Brinquedos
Name: Categoria do produto, dtype: object

In [144]:
df_produtos['Categoria do produto'].unique()

array(['Alimentos', 'Brinquedos', 'Roupas', 'Livros', 'Eletrônicos'],
      dtype=object)

In [145]:
set(df_produtos['Categoria do produto'])

{'Alimentos', 'Brinquedos', 'Eletrônicos', 'Livros', 'Roupas'}

Filtrando elementos de um DataFrame

In [146]:
df_produtos[df_produtos['Categoria do produto'] == 'Eletrônicos']

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
9,Produto 10,Eletrônicos,418.61,829,1.3
14,Produto 15,Eletrônicos,174.22,411,3.7
20,Produto 21,Eletrônicos,411.74,846,1.0
26,Produto 27,Eletrônicos,366.08,319,4.5
30,Produto 31,Eletrônicos,492.04,953,4.5
35,Produto 36,Eletrônicos,130.57,94,4.2
45,Produto 46,Eletrônicos,28.98,580,2.1

In [147]:
df_produtos[df_produtos['Avaliação do produto'] < 2]

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
3,Produto 4,Brinquedos,229.73,613,1.7
4,Produto 5,Alimentos,170.04,523,1.8
9,Produto 10,Eletrônicos,418.61,829,1.3
11,Produto 12,Roupas,308.50,867,1.2
18,Produto 19,Roupas,18.66,698,1.9
20,Produto 21,Eletrônicos,411.74,846,1.0
22,Produto 23,Roupas,119.46,129,1.4
23,Produto 24,Roupas,458.95,524,1.4
40,Produto 41,Brinquedos,36.87,920,1.2
44,Produto 45,Brinquedos,430.45,165,1.9
46,Produto 47,Livros,266.66,891,1.8

In [148]:
df_produtos.shape

(50, 5)

In [149]:
df_produtos[(df_produtos['Categoria do produto'] == 'Eletrônicos') & (df_produtos['Preço do produto'] < 250)]

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
14,Produto 15,Eletrônicos,174.22,411,3.7
35,Produto 36,Eletrônicos,130.57,94,4.2
45,Produto 46,Eletrônicos,28.98,580,2.1

In [150]:
df_produtos.iloc[10]

Nome do produto         Produto 11
Categoria do produto        Livros
Preço do produto            205.78
Itens vendidos                 863
Avaliação do produto           2.6
Name: 10, dtype: object

In [151]:
df_produtos.iloc[2:45]

,Nome do produto,Categoria do produto,Preço do produto,Itens vendidos,Avaliação do produto
2,Produto 3,Brinquedos,171.81,168,4.1
3,Produto 4,Brinquedos,229.73,613,1.7
4,Produto 5,Alimentos,170.04,523,1.8
5,Produto 6,Roupas,88.68,439,4.8
6,Produto 7,Roupas,259.04,84,2.5
7,Produto 8,Livros,175.83,189,2.7
8,Produto 9,Alimentos,167.06,396,4.0
9,Produto 10,Eletrônicos,418.61,829,1.3
10,Produto 11,Livros,205.78,863,2.6
11,Produto 12,Roupas,308.50,867,1.2
12,Produto 13,Alimentos,35.40,760,3.3
13,Produto 14,Alimentos,229.25,644,4.1
14,Produto 15,Eletrônicos,174.22,411,3.7
15,Produto 16,Brinquedos,173.47,993,5.0
16,Produto 17,Livros,258.05,104,4.5
17,Produto 18,Brinquedos,21.77,802,3.7
18,Produto 19,Roupas,18.66,698,1.9
19,Produto 20,Alimentos,404.81,422,4.1
20,Produto 21,Eletrônicos,411.74,846,1.0
21,Produto 22,Brinquedos,134.29,880,3.3
22,Produto 23,Roupas,119.46,129,1.4
23,Produto 24,Roupas,458.95,524,1.4
24,Produto 25,Roupas,353.13,217,4.6
25,Produto 26,Brinquedos,208.83,624,3.9
26,Produto 27,Eletrônicos,366.08,319,4.5
27,Produto 28,Alimentos,466.94,172,3.2
28,Produto 29,Alimentos,45.75,368,4.8
29,Produto 30,Roupas,406.05,34,4.7
30,Produto 31,Eletrônicos,492.04,953,4.5
31,Produto 32,Roupas,370.93,383,4.8
32,Produto 33,Brinquedos,211.96,262,2.2
33,Produto 34,Roupas,406.85,272,3.9
34,Produto 35,Roupas,170.46,810,2.8
35,Produto 36,Eletrônicos,130.57,94,4.2
36,Produto 37,Alimentos,187.69,537,2.8
37,Produto 38,Alimentos,156.55,988,4.8
38,Produto 39,Livros,297.26,188,2.6
39,Produto 40,Livros,61.79,568,3.1
40,Produto 41,Brinquedos,36.87,920,1.2
41,Produto 42,Roupas,62.33,943,4.7
42,Produto 43,Roupas,435.29,386,2.6
43,Produto 44,Brinquedos,102.36,762,3.4
44,Produto 45,Brinquedos,430.45,165,1.9

In [152]:
df_produtos_indice = df_produtos.set_index('Nome do produto')

In [153]:
df_produtos_indice.loc["Produto 45", "Categoria do produto"]

'Brinquedos'

In [154]:
df_produtos_indice.loc[["Produto 45", "Produto 44", "Produto 43"], ["Categoria do produto", "Preço do produto"]]

                Categoria do produto  Preço do produto
Nome do produto
Produto 45                Brinquedos            430.45
Produto 44                Brinquedos            102.36
Produto 43                    Roupas            435.29

Desafio de reviews com Pandas

In [155]:
!pip install groq --quiet
from groq import Groq
import os

In [156]:
os.environ["GROQ_API_KEY"] = userdata.get("Groq_API_key")
client = Groq()

In [157]:
df = pd.read_csv('reviews.csv')

In [158]:
df.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0

In [159]:
reviews = df['reviewText']
feedback = []

In [160]:
feedback = []

for review in reviews:
    completion = client.chat.completions.create(
        model="llama-3.1-8b-instant",
        messages=[
            {
                "role": "user",
                "content": f"Classifique essa review como positiva, negativa ou neutra. Só digite uma das 3 e mais nada: {review}"
            }
        ],
        temperature=0,
        max_completion_tokens=10
    )

    resposta = completion.choices[0].message.content
    feedback.append(resposta)

In [161]:
df['Feedback'] = feedback

In [162]:
df.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,Feedback
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0,Neutra
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0,Positiva
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0,Positiva
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0,Positiva
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0,Positiva